server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    # 毫秒
    timeout: 10000
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 5
        min-idle: 0

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.zs.modules.*.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: assign_id
    # 控制台是否开启mybatis-plus logo
    banner: false
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true