version: '1.0'
name: zs-admin
displayName: zs-admin
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-c725e0e1
    displayName: docker构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: registry-vpc.cn-zhangjiakou.aliyuncs.com
        username: 704347074@qq.com
        password: mydocker..
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./zs-admin/Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
